### ISSUE TITLE
Question: Drop-in replacement for tape?

### ISSUE THREAD

**Issue by styfle** [Rich-Harris/tape-modern#2]
Is the API for [tape-modern](https://packagephobia.now.sh/result?p=tape-modern@1.0.1) identical to [tape](https://packagephobia.now.sh/result?p=tape@4.9.0)?

If not, which exports are missing?

**Comment by Rich-Harris** [comment]
Answered on [Twitter](https://twitter.com/Rich_Harris/status/1012003957344997376) so I'll close this (sorry for missing it previously!)

It's not identical, no. There's no `t.plan` or `t.end`, because it's expected that you'll return a promise (or, rather, use an `async` function) which I think has much better ergonomics. It also doesn't have all the assertions that tape does, e.g. `t.deepEqual` (though those could be added in future).
